services:
  location-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: filomena19
      MYSQL_DATABASE: hogar360_location
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql




